specVersion: 0.2.0
name: darwinia-nft-subql
version: 0.0.4
description: Darwinia Plo NFT claim address remark
repository: https://github.com/darwinia-network/darwinia-nft-subql.git
schema:
  file: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
dataSources:
  - kind: substrate/Runtime
    startBlock: 9424555
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleSystemRemarkCall
          kind: substrate/CallHandler
          filter:
            module: system
            method: remark
            success: true
